### ISSUE TITLE
Imports not properly formatted in generated file

### ISSUE THREAD

**Issue by AdeelTariq** [InsertKoinIO/koin-annotations#13]
I'm trying to annotate a ViewModel like this with both @KoinViewModel and @Scope

```
@KoinViewModel
@Scope(ExampleFragment::class)
class ExampleViewModel: ViewModel()

```

The project has already been using koin-android 3.1.5 successfully. I have done no other change in the code except the ones mentioned in the readme.

The imports in the resulting generated code are not properly formatted:

```
package org.koin.ksp.generated

import org.koin.core.KoinApplication
import org.koin.core.module.Module
import org.koin.dsl.*import org.koin.core.qualifier.StringQualifierimport org.koin.androidx.viewmodel.dsl.viewModel
import org.koin.androidx.viewmodel.dsl.viewModel
fun KoinApplication.defaultModule() = modules(defaultModule)
val defaultModule = module {
	scope<com.example.ExampleFragment> {
			viewModel(qualifier=null) { com.example.ExampleViewModel() }
	}
}
```

**Koin project used and used version:**
`koin-android version 3.2.0-beta-1`
`koin-annotations version 1.0.0-beta-1`

**Comment by joeypatino** [comment]
@AdeelTariq How were you able to fix this issue? I'm also seeing the same thing when trying to use @KoinViewModel annotations

**Comment by AdeelTariq** [comment]
Using the newest version should fix it

**Comment by joeypatino** [comment]
Odd. I'm using the latest versions of ksp(1.6.21-1.0.5), koin annotations(1.0.0-beta-2) and koin (3.2.0-beta-1) but still have the error. Could you share which versions you're using in your gradle file?
