### ISSUE TITLE
Generated modules use deprecated APIs when used in combination with Koin 4.0.0

### ISSUE THREAD

**Issue by pikzen** [InsertKoinIO/koin-annotations#171]
**Describe the bug**
The generated code uses calls to `Module.viewModel { }` that are referencing the "old" Koin 3.5.6 API. Warnings are then emitted to the build log when using Koin 4.0.0:

```
w: /src/project/build/generated/ksp/prodRelease/kotlin/org/koin/ksp/generated/KoinDefault--104252179.kt:8:63 'fun <reified T : ViewModel> Module.viewModel(qualifier: Qualifier? = ..., noinline definition: Scope.(ParametersHolder) -> T): KoinDefinition<T>' is deprecated. Moved ViewModel DSL package. Remove old imports and use org.koin.core.module.dsl.*.
```

This is an issue, because the generated code is treated as "normal" code due to adding the generated/ sources as part of the sourceSets. If building with allWarningsAsError, the build will fail. The only solution is to downgrade koin.

**To Reproduce**
Use both Koin-Annotations 1.4.0-RC4 and Koin 4.0.0 in the same project, declare a @KoinViewModel, build.

**Expected behavior**
The generated code should not emit warnings. Ideally, swapping to another code generation solution (a compiler plugin, maybe?) would remove the necessity to include the generated code in the sourceset. Otherwise, provide an option similar to KOIN_USE_COMPOSE_VIEWMODEL like arg("KOIN_USE_TARGETED_API", "4.0") to generate code based on the target. Not making it a simple true/false option would allow you to easily change code generation should something get deprecated in, say, 4.2

**Koin project used and used version (please complete the following information):**
koin-annotations 1.4.0-RC4
koin 4.0.0

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by kibettheophilus** [comment]
Hi @pikzen , I believe this should be fixed on the next release for koin-annotations.

**Comment by arnaudgiuliani** [comment]
Yes, for now. 1.4 is still Koin 3.5.6 compat

**Comment by krzdabrowski** [comment]
At least for me, #172 did not solve the issue - it still uses `org.koin.androidx.viewmodel.dsl.viewModel` in generated code.

Using KA 2.0.0-Beta1 & Koin 4.0.

**Comment by kibettheophilus** [comment]
@krzdabrowski you are not using any of the viewmodel flags right? i.e `KOIN_USE_COMPOSE_VIEWMODEL` or `USE_COMPOSE_VIEWMODEL` , atleast that is how I have been able to reproduce.

**Comment by krzdabrowski** [comment]
@kibettheophilus no, I don't use any custom flags, just plain config following the documentation, I'm new to Koin

**Comment by kibettheophilus** [comment]
@krzdabrowski okay, adding the argument should fix this:
```
ksp {
    arg("KOIN_USE_COMPOSE_VIEWMODEL","true")
}
```

Check on: [Generate ViewModel](https://insert-koin.io/docs/reference/koin-annotations/definitions#generate-compose-viewmodel-for-kotlin-multipaltform-since-140)

I also have a sample project incase you need to make references: [https://github.com/kibettheophilus/koin-playground](https://github.com/kibettheophilus/koin-playground)

**Comment by krzdabrowski** [comment]
@kibettheophilus this fixes the issue (as we'd expect) however it addresses the issue from the different side 🙂 
This change generates KMP ViewModel as docs title suggests: "Generate Compose ViewModel for Kotlin Multipaltform (since 1.4.0)"

However, as of now, my project is Android-only and I don't have anything related with KMP here.

My expectations would be to not see the warning no matter if project is Android-only, or KMP, and which sort of ViewModel I am using.

**Comment by kibettheophilus** [comment]
> @kibettheophilus this fixes the issue (as we'd expect) however it addresses the issue from the different side 🙂 This change generates KMP ViewModel as docs title suggests: "Generate Compose ViewModel for Kotlin Multipaltform (since 1.4.0)"
> 
> However, as of now, my project is Android-only and I don't have anything related with KMP here.
> 
> My expectations would be to not see the warning no matter if project is Android-only, or KMP, and which sort of ViewModel I am using.

@krzdabrowski this still works on android only projects, check on my sample project which is android only.
