### ISSUE TITLE
KoinDefIoKtorClientHttpClient class in multiple KoinMeta's when exporting and using multiple modules

### ISSUE THREAD

**Issue by rschattauer** [InsertKoinIO/koin-annotations#186]
**Describe the bug**
Kind of like the same issue as https://github.com/InsertKoinIO/koin-annotations/issues/178 , but I wanted to create a new issue as it may be a little bit different.
I have multiple modules that are all using (for example) Ktor and I build all of them and upload them to Nexus. Once building my Android application it fails with "Duplicate class" for KoinDefIoKtorClientHttpClient.

**To Reproduce**
My KMP part is using multiple modules that are all build and exported to our Nexus. Meaning on nexus I have my.stuff:module-a:1.0.0 and my.stuff:module-b:1.0.0 which both have an http client that do different things.

Building and uploading to nexus is no issue, but using it within my android application I get the following error
```
Execution failed for task ':app:checkLongtermStageDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
     Duplicate class org.koin.ksp.generated.KoinDefIoKtorClientHttpClient found in the following modules: module-a-1.0.0-SNAPSHOT.aar -> module-a-1.0.0-SNAPSHOT-runtime (my.stuff:module-a:1.0.0-SNAPSHOT:20241112.085747-4), and module-b-1.0.0-SNAPSHOT.aar -> module-b-1.0.0-SNAPSHOT-runtime (my.stuff:module-b:1.0.0-SNAPSHOT:20241112.085747-4)
```

Ktor http client is just one example, I am facing this issue with all things that are generated using annotations.
For example also `public class KoinDefKotlinxSerializationJsonJson`

My modules look like this:
```
@org.koin.core.annotation.Module
@org.koin.core.annotation.ComponentScan
internal object ModuleA
```
&
```
@org.koin.core.annotation.Module
@org.koin.core.annotation.ComponentScan
internal object ModuleB
```
, so nothing fancy or even special.

My httpClient definition for both modules look kind of like
```
@Single
@Named("ModuleA.HttpClient")
fun moduleAHttpClient(): HttpClient = createHttpClient(..)
```

Making the definitions internal doesn't resolve this problem, I am still facing multiple creations.

**Expected behavior**
Maybe the package also needs to be applied for third party classes/dependencies?

**Koin project used and used version:**
Koin Annotation 1.4.0 & 2.0.0-Beta01

**Comment by arnaudgiuliani** [comment]
Fixed in https://github.com/InsertKoinIO/koin-annotations/pull/206

**Comment by rschattauer** [comment]
@arnaudgiuliani , this issue still exists with koin 4.0.2 and koin-annotations 2.0.0

**Comment by rschattauer** [comment]
I have a workaround for now, which is creating a wrapper class for my http clients.

```
@JvmInline
value class HttpClientA(val value: HttpClient)

@JvmInline
value class HttpClientB(val value: HttpClient)

@Single
fun moduleAHttpClient(): HttpClientA = HttpClientA(value = createHttpClient(..))

@Single
fun moduleBHttpClient(): HttpClientB = HttpClientB(value = createHttpClient(..))
```

with that I will have the package used within KoinMeta-*.kt of module A
`public class KoinDefDeMyPackageHttpClientA` 
& within module B
`public class KoinDefDeMyPackageHttpClientB`
