### ISSUE TITLE
KoinViewModel is not working as expected

### ISSUE THREAD

**Issue by ugurcany** [InsertKoinIO/koin-annotations#35]
I just switched to koin 3.2 & annots 1.0.0 versions. I'm using it in one of my android library modules. the issue is my viewmodel classes which are annotated with @KoinViewModel are defined as "factory" in autogenerated module files:

```
val com_******_presentation_stock_Stock = module {
   factory(qualifier=null) { com.******.presentation.stock.StockViewModel(get(),get(),get(),get(),get(),get(),get()) } binds(arrayOf(androidx.lifecycle.ViewModel::class,androidx.lifecycle.DefaultLifecycleObserver::class,com.******.presentation.util.ViewStateHolder::class))
}
```

**Comment by arnaudgiuliani** [comment]
yes it has been fixed in 1.0.1

**Comment by ugurcany** [comment]
no unfortunately, it's not fixed for delegates. try the following cases:

```
@KoinViewModel
class OverviewAccountViewModel constructor(
    viewState: OverviewAccountViewState,
    private val getOverviewAccounts: GetOverviewAccounts
) : ViewModel(),
    DefaultLifecycleObserver,
    ViewStateHolder<OverviewAccountViewState> by ViewStateHolderImpl(viewState)
```

**Comment by arnaudgiuliani** [comment]
I don't see the problem here 🤔 It's generated as `viewModel` else it's another issue

**Comment by arnaudgiuliani** [comment]
No better update? Still getting problem with delegate?

**Comment by Kashif-E** [comment]
Still facing this issue on the latest release 

```kotlin 
@Factory(binds = [BaseScreenModel::class,])
class ManagePlansScreenModel(
    currentPlan: PricingPlan? = null,
    renewalDate: String? = null
) : BaseScreenModel<ManagePlansState, ManagePlansAction, ManagePlansEvent>(
    initialState = ManagePlansState(
        currentPlan = currentPlan,
        renewalDate = renewalDate
    )
) {

```
```kotlin 
@Factory
class IapScreenModel(
    @InjectedParam()
    private val currentUserPlan: PricingPlan? = null
) : BaseScreenModel<IapScreenState, IapScreenAction, IapScreenEvent>(
    initialState = IapScreenState(
        selectedPlan = currentUserPlan ?: PricingPlan.Monthly,
        currentUserPlan = currentUserPlan
    )
) 
```

generated only for one screemodel 
```Kotlin 
public val com_vyro_chatlymobile_featureiap_presentation_iapscreen_di_IapModule : Module get() = module {
	factory() { params -> com.vyro.chatlyMobile.featureIap.presentation.iapScreen.mvi.IapScreenModel() } bind(com.vyro.core.presentation.BaseScreenModel::class)
}
public val com.vyro.chatlyMobile.featureIap.presentation.iapScreen.di.IapModule.module : org.koin.core.module.Module get() = com_vyro_chatlymobile_featureiap_presentation_iapscreen_di_IapModule
```

**Comment by arnaudgiuliani** [comment]
@Kashif-E you only have one super type, 'BaseScreenModel' here. Where is the problem?
